<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/00_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
##Pytorch tutorial from FreeCodeCamp

dziala


In [2]:
import torch
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


**Introduction to Tensors**

PyTorch tensors are createdy using `torch.Tensor()`

In [3]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
#Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [24]:
#MATRIX
MATRIX = torch.tensor([[7, 8, 9],
                       [9, 10, 11]])
MATRIX

tensor([[ 7,  8,  9],
        [ 9, 10, 11]])

In [25]:
MATRIX.ndim

2

In [26]:
MATRIX[0]

tensor([7, 8, 9])

In [27]:
MATRIX.shape

torch.Size([2, 3])

In [21]:
#TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]], [[2, 4, 6],
                                     [3, 7, 10],
                                     [2, 2, 2]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 2,  4,  5]],

        [[ 2,  4,  6],
         [ 3,  7, 10],
         [ 2,  2,  2]]])

In [22]:
TENSOR.ndim

3

In [23]:
TENSOR.shape

torch.Size([2, 3, 3])