<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/01_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Creating a Tensors**

In [4]:
import torch
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [13]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0982, 0.9152, 0.1010, 0.2624],
        [0.4599, 0.8500, 0.9347, 0.9899],
        [0.9244, 0.4660, 0.3369, 0.4549]])

In [11]:
#Create a random tensor with similar shapte to an image tensor
random_image_size_tensor = torch.rand(size=(3,244, 244)) #Color RGB Heigth, Witdh
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [14]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [16]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
ones.dtype

torch.float32

###Create a range

In [24]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11) #start, end, step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])