<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/01_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**Creating a Tensors**

In [2]:
import torch
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

print(torch.__version__)

2.4.1+cu121


### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

In [ ]:
#Create a random tensor of size (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0982, 0.9152, 0.1010, 0.2624],
        [0.4599, 0.8500, 0.9347, 0.9899],
        [0.9244, 0.4660, 0.3369, 0.4549]])

In [ ]:
#Create a random tensor with similar shapte to an image tensor
random_image_size_tensor = torch.rand(size=(3,244, 244)) #Color RGB Heigth, Witdh
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([244, 244, 3]), 3)

### Zeros and ones

In [ ]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Create a tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

###Create a range

In [ ]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(1, 11) #start, end, step
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensors datatypes ***(Attributes)***

**Note:** Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & dl
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [8]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, #What datatype is tensor
                               device=None,  #cpu || gpu || cuda
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor, float_32_tensor.dtype, float_32_tensor.device

(tensor([3., 6., 9.]), torch.float32, device(type='cpu'))

In [9]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [12]:
(float_32_tensor + float_32_tensor) * float_32_tensor

tensor([ 18.,  72., 162.])

In [14]:
int_32_tensor = torch.tensor([3,6,9], dtype=torch.int32)
int_32_tensor*float_32_tensor

tensor([ 9., 36., 81.])

**Getting information from tensors**
Tensors not right datatype - can use `tensor.dtype `
Tensors not right shape - can use `tensor.shape`
Tensors not on the right device - can use `tensor.device`

In [15]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.6775, 0.0689, 0.3236, 0.4026],
        [0.7100, 0.3597, 0.3787, 0.4414],
        [0.0044, 0.0985, 0.7032, 0.4078]])

In [17]:
#Find out details about some tensors
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.6775, 0.0689, 0.3236, 0.4026],
        [0.7100, 0.3597, 0.3787, 0.4414],
        [0.0044, 0.0985, 0.7032, 0.4078]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [18]:
tensor = torch.tensor([1, 2, 3])
tensor + 10 # or torch.add(tensor, 10)

tensor([11, 12, 13])

In [19]:
tensor * 10
# or torch.mul(tensor, 10)

tensor([10, 20, 30])

In [20]:
tensor - 10

tensor([-9, -8, -7])