<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/02_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Matrix multiplication***

In [1]:
import torch
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.0+cu121


Two main ways of performing multiplication in neural networks and dl:
1. Element-wise multiplication
2. Matrix multliplication (dot product)

Two main rules of performing matrix multiplication:
1. inner dimensions must match:
- (3, 2) * (3, 2) won't work
- (3, 2) * (2, 3) will work
- (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of the **outer dimensions**
- (2, **3**) * (**3**, 2) -> (2, 2)
- (3, **2**) * (**2**, 5) -> (3, 5)

In [ ]:
matrix1 = torch.tensor([[1, 2, 3],
                        [3, 1, 2],
                        [5, 3, 1]])
matrix2 = torch.tensor([[4, 5],
                        [1, 3],
                        [7, 9]])
torch.matmul(matrix1, matrix2)

tensor([[27, 38],
        [27, 36],
        [30, 43]])

In [ ]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 5))

tensor([[1.4910, 0.8382, 0.8250, 1.3993, 0.5400],
        [1.3877, 0.7785, 0.4424, 1.2124, 0.5411],
        [1.2866, 0.8623, 0.6864, 1.2793, 0.3941]])

In [ ]:
#SHAPE ERROR. THIS CODE IS WRONG
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]]) #num of rows in matrix2 must be =
tensor_B = torch.tensor([[7, 8],  #num of scalars in one row in matrix1
                         [9, 10],
                         [11, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

**transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
#The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, avg (mean), sum



In [5]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [3]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [4]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [8]:
#Find the avg --- Note: x is long type. .mean() can't work with long type
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [7]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max - ***argmin(), argmax()***

In [9]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
x.argmin()

tensor(0)

In [11]:
x.argmax()

tensor(9)

### Reshaping, viewing and stacking, squeezing and unsqueezing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the originaml tensor
* Stacking - combine multiple on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Premute - return a view of the input with dimensions permuted (swapped) in a certain way

In [33]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [46]:
# add an extra dimension (reshape)
x_reshaped = x.reshape(1, 10) # 10 == sizeOfTensor
x_reshaped, x_reshaped.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [48]:
# change the view
z = x_reshaped.view(1, 10)
z, z.shape
#Changing z changes x (cause a view of a tensor shares the same memory as the original input)

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [36]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [42]:
#Stack tensors on top of each other (vstack)
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [41]:
#Stack tensors side by side (hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [49]:
# squeeze
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_squeezed, x_squeezed.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]))

In [55]:
# unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_squeezed, x_squeezed.shape, x_unsqueezed, x_unsqueezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [59]:
# permute
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

#Premute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #first index nr 2, next 0 and 1 to the end

x_original.shape, x_permuted.shape
#[height, width, colour_channels] -> [colour_channels, height, width]

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))