<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/02_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Matrix multiplication***

In [1]:
import torch
import pandas as pd
import numpy as nm
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.0+cu121


Two main ways of performing multiplication in neural networks and dl:
1. Element-wise multiplication
2. Matrix multliplication (dot product)

Two main rules of performing matrix multiplication:
1. inner dimensions must match:
- (3, 2) * (3, 2) won't work
- (3, 2) * (2, 3) will work
- (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of the **outer dimensions**
- (2, **3**) * (**3**, 2) -> (2, 2)
- (3, **2**) * (**2**, 5) -> (3, 5)

In [11]:
matrix1 = torch.tensor([[1, 2, 3],
                        [3, 1, 2],
                        [5, 3, 1]])
matrix2 = torch.tensor([[4, 5],
                        [1, 3],
                        [7, 9]])
torch.matmul(matrix1, matrix2)

tensor([[27, 38],
        [27, 36],
        [30, 43]])

In [27]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 5))

tensor([[1.4910, 0.8382, 0.8250, 1.3993, 0.5400],
        [1.3877, 0.7785, 0.4424, 1.2124, 0.5411],
        [1.2866, 0.8623, 0.6864, 1.2793, 0.3941]])

In [28]:
#SHAPE ERROR. THIS CODE IS WRONG
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]]) #num of rows in matrix2 must be =
tensor_B = torch.tensor([[7, 8],  #num of scalars in one row in matrix1
                         [9, 10],
                         [11, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [31]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

**transpose** switches the axes or dimensions of a given tensor

In [33]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [34]:
#The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])