<a href="https://colab.research.google.com/github/AdamStajer07/pytorchTutorial/blob/main/02_pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***Matrix multiplication***

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.5.0+cu121


Two main ways of performing multiplication in neural networks and dl:
1. Element-wise multiplication
2. Matrix multliplication (dot product)

Two main rules of performing matrix multiplication:
1. inner dimensions must match:
- (3, 2) * (3, 2) won't work
- (3, 2) * (2, 3) will work
- (2, 3) * (3, 2) will work
2. The resulting matrix has the shape of the **outer dimensions**
- (2, **3**) * (**3**, 2) -> (2, 2)
- (3, **2**) * (**2**, 5) -> (3, 5)

In [ ]:
matrix1 = torch.tensor([[1, 2, 3],
                        [3, 1, 2],
                        [5, 3, 1]])
matrix2 = torch.tensor([[4, 5],
                        [1, 3],
                        [7, 9]])
torch.matmul(matrix1, matrix2)

tensor([[27, 38],
        [27, 36],
        [30, 43]])

In [ ]:
torch.matmul(torch.rand(3, 4), torch.rand(4, 5))

tensor([[1.5545, 1.3960, 2.2455, 1.0916, 1.6922],
        [0.9134, 1.2783, 1.5736, 0.8424, 1.4658],
        [1.3844, 1.2036, 2.0112, 1.0177, 1.4431]])

In [ ]:
#SHAPE ERROR. THIS CODE IS WRONG
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]]) #num of rows in matrix2 must be =
tensor_B = torch.tensor([[7, 8],  #num of scalars in one row in matrix1
                         [9, 10],
                         [11, 12]])
torch.mm(tensor_A, tensor_B) #torch.mm() is the same as torch.matmul()

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7,  8],
         [ 9, 10],
         [11, 12]]),
 torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**

**transpose** switches the axes or dimensions of a given tensor

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [ ]:
#The matrix multiplication operation works when tensor_B is transposed

torch.mm(tensor_A, tensor_B.T)

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

### Finding the min, max, avg (mean), sum



In [ ]:
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [ ]:
#Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
#Find the avg --- Note: x is long type. .mean() can't work with long type
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Finding the positional min and max - ***argmin(), argmax()***

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
x.argmin()

tensor(0)

In [ ]:
x.argmax()

tensor(9)

### Reshaping, viewing and stacking, squeezing and unsqueezing tensor
* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the originaml tensor
* Stacking - combine multiple on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Premute - return a view of the input with dimensions permuted (swapped) in a certain way

In [ ]:
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
# add an extra dimension (reshape)
x_reshaped = x.reshape(1, 10) # 10 == sizeOfTensor
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# change the view
z = x_reshaped.view(2, 5)
z, z.shape
#Changing z changes x (cause a view of a tensor shares the same memory as the original input)

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [ ]:
z[:, 0] = 5
z, x

(tensor([[ 5.,  2.,  3.,  4.,  5.],
         [ 5.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]))

In [ ]:
#Stack tensors on top of each other (vstack)
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
        [ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]])

In [ ]:
#Stack tensors side by side (hstack)
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 5.,  5.,  5.,  5.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

In [ ]:
# squeeze
x_squeezed = x_reshaped.squeeze()
x_reshaped, x_reshaped.shape, x_squeezed, x_squeezed.shape

(tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]),
 torch.Size([10]))

In [ ]:
# unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_squeezed, x_squeezed.shape, x_unsqueezed, x_unsqueezed.shape

(tensor([ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]),
 torch.Size([10]),
 tensor([[ 5.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
# permute
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

#Premute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #first index nr 2, next 0 and 1 to the end

x_original.shape, x_permuted.shape
#[height, width, colour_channels] -> [colour_channels, height, width]

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [ ]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0], x[0, 0] #It's the same

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
x[0, 0, 0]

tensor(1)

In [ ]:
x[:,2,2]

tensor([9])

In [ ]:
x[:,:, 1].reshape(3, 1)

tensor([[2],
        [5],
        [8]])

In [ ]:
x[0,0,:]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor => NumPy - `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32) # Default dtype of tensor is float32
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#Change the value of array

array = array * 2
array, tensor
#remain the same

(array([ 2.,  4.,  6.,  8., 10., 12., 14.]),
 tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
#tensor to numpy array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, tensor.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))

In [ ]:
#Change the tensor
tensor = tensor * 2
tensor, numpy_tensor
#remain the same

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network leanrs:
`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**

Essentially what the random seed does is "flavour" the randomness

Docs: https://pytorch.org/docs/stable/notes/randomness.html

In [6]:
#create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.1386, 0.2368, 0.9025, 0.8458],
        [0.8090, 0.5178, 0.4941, 0.1316],
        [0.4057, 0.1586, 0.3439, 0.6307]])
tensor([[0.4319, 0.8146, 0.9193, 0.6540],
        [0.7659, 0.9618, 0.0486, 0.1347],
        [0.6983, 0.3342, 0.2759, 0.6064]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [17]:
# random but reproducible tensors
# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
tensor = torch.tensor([1, 2, 3])

tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [4]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [5]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

Excersizes
https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises